### ISSUE TITLE
e.response is not accessible

### ISSUE THREAD

**Issue by jonmchan** [opti/panda_doc#11]
The [documentation](https://github.com/opti/panda_doc#error-handling) seems to indicate that `e.response` is available when catching errors.

Excerpt:

```
begin
  PandaDoc::Document.create(name: "Sample Document")
rescue PandaDoc::FailureResult => e
  puts e.detail
  puts e.response
end
```

 However, the response method is private on `PandaDoc::FailureResult`.

I receive the following error:
```
NoMethodError (private method `response' called for #<PandaDoc::FailureResult: 409 : >
```

Please make the response method public.

**Comment by opti** [comment]
Thanks for reporting. Fixed in [v0.6.0](https://github.com/opti/panda_doc/blob/main/CHANGELOG.md#060-2022-05-04)
