### ISSUE TITLE
Feature request - ability to list documents

### ISSUE THREAD

**Issue by brycesenz** [opti/panda_doc#45]
I really appreciate all of the hard work in this library!  It has been great for all of our use cases except for one - listing the existing documents, which seems to be a pretty standard part of the API (https://developers.pandadoc.com/reference/list-documents)

I would love to see this query method supported in this gem.

**Comment by opti** [comment]
Thank you for your kind words. If you'd like to give it a try, feel free to open a pull request.

**Comment by opti** [comment]
@brycesenz I've added `PandaDoc::Document.list` in this PR https://github.com/opti/panda_doc/pull/46. Please, give it a try and let me know it that works for you.

**Comment by opti** [comment]
I've just published v0.9.0
