### ISSUE TITLE
Dry::Struct::Error ([PandaDoc::Objects::Recipient.new] :has_completed is missing in Hash input):

### ISSUE THREAD

**Issue by edouardswiac** [opti/panda_doc#8]
When calling 

```ruby
    PandaDoc::Document.send(document.uuid, message: "A message to include into the email")
```

Looks like this field is not returned anymore maybe?  Similar to https://github.com/opti/panda_doc/issues/5

Thanks for the great gem!

**Comment by opti** [comment]
Fixed in [v0.6.0](https://github.com/opti/panda_doc/blob/main/CHANGELOG.md#060-2022-05-04)
